# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 66c5be7bfed589b1b143776ce1f4dff20089845e3af74b14dfed566cf54509cec909c9928bd9ffe6088b9619e97a81cdc9928d0b5c81d8f12267211851234b3f

test:
  secret_key_base: 362f4d87b2fb92267b58acf2061bc203d562570651269b434cd999d4ce274abacf0c25c3c87f719b9bc1fc2093a92804b6ab37d68ac24311458bf02281842361

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
